---
title: "Calculating SO2 from pO2"
author: "B Sanderson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The relationship of haemoglobin oxygen saturation $S_{O_2}$ of haemoglobin to the partial pressure of oxygen $p_{O_2}$ in blood is described by the [oxygen dissociation curve.](https://en.wikipedia.org/wiki/Oxygen%E2%80%93hemoglobin_dissociation_curve) This sigmoiodal curve describes haemoglobin's affinity for oxygen, characterising how it acquires and releases oxygen. The shape and position of the curve is affected by several factors, pH, temperature, concentration of 2,3-BPG and $p_{CO_2}$

Many, increasingly accurate, models describing this relationship have been published. The two functions presented here are based on work of @kelman_1966. This model is inacccurate as $p_{O_2}$ approaches 0, but is otherwise an excellent fit to physiologically occuring values.

## Theory

The mathematical model @kelman_1966 used to describe the dissociation curve takes the following form:

$$
\begin{equation}
S_{O_2} = 100 \cdot \frac {a_1 \cdot p_{O_2} + a_2 \cdot p_{O_2}^2 + a_3 \cdot p_{O_2}^3 + p_{O_2}^4}{a_5 \cdot p_{O_2} + a_6 \cdot p_{O_2}^2 + a_7 \cdot p_{O_2}^3 + p_{O_2}^4}
\end{equation}
$$

where:

$$
\begin{aligned}
a_1 &=  -8.5322289 \times 10^3 \\
a_2 &=  2.1214010 \times 10^3 \\
a_3 &=  -6.7073989 \times 10^1 \\
a_4 &=  9.3596087 \times 10^5 \\
a_5 &=  -3.1346258 \times 10^4 \\
a_6 &=  2.3961674 \times 10^3 \\
a_7 &=  -6.7104406 \times 10^1
\end{aligned}
$$
@kelman_1966 stated that the form extends the work of @Adair_1925, and as such is entirely pragmatic, and as such is not intended to confirm that human haemoglobin binds to oxygen in the manner described by Adair.



## References
